---

- name: Verify
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  tasks:
    - name: Get all pods in {{ namespace }}
      k8s_facts:
        api_version: v1
        kind: Pod
        namespace: '{{ namespace }}'
      register: pods

    - name: Output pods
      debug: var=pods

    - name: set fact for present
      set_fact:
        state: "present"

- import_playbook: '{{ playbook_dir }}/../default/asserts_kube_resources.yml'
