kind: ServiceAccount
apiVersion: v1
metadata:
  name: etcd-ha-operator

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: etcd-ha-operator
rules:
- apiGroups:
  - etcd.database.coreos.com
  - extensions
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: account-app-operator
  namespace: {{ namespace  }}
subjects:
- kind: ServiceAccount
  name: etcd-ha-operator
  namespace: {{ namespace  }}
roleRef:
  kind: ClusterRole
  name: etcd-ha-operator
  apiGroup: rbac.authorization.k8s.io