---
- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  roles:
    - etcdcluster

- import_playbook: '{{ playbook_dir }}/verify.yml'
